apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: jackswebbrand/payments
          env:
            - name: STRIPE_KEY #Just a name for us
              valueFrom:
                secretKeyRef:
                  name: stripe-secret # The actual name of the secret inside the cluster
                  key: STRIPE_KEY
            - name: JWT_KEY #Just a name for us
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # The actual name of the secret inside the cluster
                  key: JWT_KEY
            - name: MONGO_URI
              value: 'mongodb://payments-mongo-srv:27017/payments'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              memory: '512Mi'
              cpu: '500m'
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
